# Assignment 3 - Data Cleaning and Analysis

이번 과제에서 학생들은 주어진 데이터를 clean up 하고 분석하는 연습을 하게 될 것이다.

두개의 지정된 질문에 대한 답을 하여야 하고 세개의 질문을 스스로 만들어 코드와 함께 결과를 제시한다.

* 파일 이름: A3-학번-이름(영어로).iphynb 형식으로 (예: A3-13403-999-jiyoon.iphynb)

### Dataset

타이타닉호의 모든 승객, 승무원의 정보와 생존자, 사망자 정보는 다음의 웹사이트에 잘 정리되어있다.
* http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic.html

본 과제에서 제시하는 데이터는 해당 웹사이트의 정보를 담고 있다. 다음의 데이터를 다운로드하여 분석하고 아래의 질문에 답하시오.
* 데이터: http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.xls
* 데이터 설명: http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic.html
* 데이터 변수 설명: http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3info.txt

In [1]:
import pandas as pd
import numpy as np
data_origin = pd.read_excel("titanic3.xls")
data_origin.head()

pclass  survived                                             name     sex  \
0       1         1                    Allen, Miss. Elisabeth Walton  female   
1       1         1                   Allison, Master. Hudson Trevor    male   
2       1         0                     Allison, Miss. Helen Loraine  female   
3       1         0             Allison, Mr. Hudson Joshua Creighton    male   
4       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   

       age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0  29.0000      0      0   24160  211.3375       B5        S    2    NaN   
1   0.9167      1      2  113781  151.5500  C22 C26        S   11    NaN   
2   2.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3  30.0000      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4  25.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON  
4  Montreal, PQ / Chesterville, ON

### Q1: 생존자와 사망자의 평균 나이를 남녀를 구분하여 계산하시오.

In [2]:
data1 = data_origin[["survived", "sex", "age","fare"]]

data_survived = data1[data1["survived"]==1]
print(data_survived.head())
data_died = data1[data1["survived"]==0]
print(data_died.head())

   survived     sex      age      fare
0         1  female  29.0000  211.3375
1         1    male   0.9167  151.5500
5         1    male  48.0000   26.5500
6         1  female  63.0000   77.9583
8         1  female  53.0000   51.4792
   survived     sex   age      fare
2         0  female   2.0  151.5500
3         0    male  30.0  151.5500
4         0  female  25.0  151.5500
7         0    male  39.0    0.0000
9         0    male  71.0   49.5042


In [3]:
print("생존자 평균 나이")
data_survived_mean = data_survived["age"].groupby(data_survived["sex"])
print(data_survived_mean.mean())

생존자 평균 나이
sex
female    29.815354
male      26.977778
Name: age, dtype: float64


In [4]:
print("사망자 평균 나이")
data_died_mean = data_died["age"].groupby(data_died["sex"])
print(data_died_mean.mean())

사망자 평균 나이
sex
female    25.255208
male      31.516412
Name: age, dtype: float64


### Q2: 생존자의 평균 티켓 가격과 사망자의 평균 티켓 가격을 구하고 비교하시오.

In [5]:
ticket_mean = data1["fare"].groupby(data1["survived"])
ticket_mean.mean()

survived
0    23.353831
1    49.361184
Name: fare, dtype: float64

### Q3: First class, Second Class, Third class의 생존 비율을 구하고 비교하시오.

In [6]:
#가정 : 더 높은 class의 passenger가 더 많이 생존했을 것이다.

In [7]:
data2 = data_origin[["pclass","survived","age","sex"]]

data_class1 = data2[data2["pclass"]==1]
print(data_class1.head())


data_class2 = data2[data2["pclass"]==2]
print(data_class2.head())

data_class3 = data2[data2["pclass"]==3]
print(data_class3.head())


   pclass  survived      age     sex
0       1         1  29.0000  female
1       1         1   0.9167    male
2       1         0   2.0000  female
3       1         0  30.0000    male
4       1         0  25.0000  female
     pclass  survived   age     sex
323       2         0  30.0    male
324       2         1  28.0  female
325       2         0  30.0    male
326       2         0  18.0    male
327       2         0  25.0    male
     pclass  survived   age     sex
600       3         0  42.0    male
601       3         0  13.0    male
602       3         0  16.0    male
603       3         1  35.0  female
604       3         1  16.0  female


In [8]:
prob_1 = len(data_class1[data_class1["survived"]==1])/len(data_class1)
print("First class : "+str(prob_1))
prob_2 = len(data_class2[data_class2["survived"]==1])/len(data_class2)
print("Second class : "+str(prob_2))
prob_3 = len(data_class3[data_class3["survived"]==1])/len(data_class3)
print("Third class : "+str(prob_3))

First class : 0.6191950464396285
Second class : 0.4296028880866426
Third class : 0.2552891396332863


### Q4: 각 class별 생존자 대비 여성 비율, 여성 중 생존한 사람의 비율을 구하시오 

In [9]:
#가설 : first class 여성의 생존 비율이 가장 높을 것이다. 
#가설 : 여성의 생존 비율은 모든 class에서 높을 것이다.
#가설 : class가 높을 수록 여성의 생존 비율도 높아질 것이다.

In [10]:
data_class1_s = data_class1[data_class1["survived"]==1]
prob_c1_1 = len(data_class1_s[data_class1_s["sex"]=="female"])/len(data_class1)
prob_c1_2 = len(data_class1_s[data_class1_s["sex"]=="female"])/len(data_class1_s)
prob_c1_3 = len(data_class1_s[data_class1_s["sex"]=="female"])/len(data_class1[data_class1["sex"]=="female"])
class1 = np.array([prob_c1_1, prob_c1_2, prob_c1_3])
class1_1 = np.array([len(data_class1),len(data_class1_s),len(data_class1[data_class1["sex"]=="female"]),len(data_class1_s[data_class1_s["sex"]=="female"])])
print(class1)
print(class1_1)

[0.43034056 0.695      0.96527778]
[323 200 144 139]


In [11]:
data_class2_s = data_class2[data_class2["survived"]==1]
prob_c2_1 = len(data_class2_s[data_class2_s["sex"]=="female"])/len(data_class2)
prob_c2_2 = len(data_class2_s[data_class2_s["sex"]=="female"])/len(data_class2_s)
prob_c2_3 = len(data_class2_s[data_class2_s["sex"]=="female"])/len(data_class2[data_class2["sex"]=="female"])
class2 = np.array([prob_c2_1, prob_c2_2, prob_c2_3])
class2_1 = np.array([len(data_class2),len(data_class2_s),len(data_class2[data_class2["sex"]=="female"]),len(data_class2_s[data_class2_s["sex"]=="female"])])
print(class2)
print(class2_1)

[0.33935018 0.78991597 0.88679245]
[277 119 106  94]


In [12]:
data_class3_s = data_class3[data_class3["survived"]==1]
prob_c3_1 = len(data_class3_s[data_class3_s["sex"]=="female"])/len(data_class3)
prob_c3_2 = len(data_class3_s[data_class3_s["sex"]=="female"])/len(data_class3_s)
prob_c3_3 = len(data_class3_s[data_class3_s["sex"]=="female"])/len(data_class3[data_class3["sex"]=="female"])
class3 = np.array([prob_c3_1, prob_c3_2, prob_c3_3])
class3_1 = np.array([len(data_class3),len(data_class3_s),len(data_class3[data_class3["sex"]=="female"]),len(data_class3_s[data_class3_s["sex"]=="female"])])
print(class3)
print(class3_1)

[0.14950635 0.58563536 0.49074074]
[709 181 216 106]


In [13]:
class_combine = np.array([class1, class2, class3])
col_name = ["전체 대비 생존 여성 비율","전체 생존자 중 여성의 비율","여성 중 생존자 비율"]
index_name = ["First class", "Second class", "Third class"]
table_woman_prob = pd.DataFrame(class_combine, columns = col_name, index = index_name)
print(table_woman_prob)

class_combine2=np.array([class1_1, class2_1, class3_1])
col_name2=["전체","생존자 수", "여성의 수", "생존 여성의 수"]
table_woman=pd.DataFrame(class_combine2, columns = col_name2, index = index_name)

print(table_woman)


              전체 대비 생존 여성 비율  전체 생존자 중 여성의 비율  여성 중 생존자 비율
First class         0.430341         0.695000     0.965278
Second class        0.339350         0.789916     0.886792
Third class         0.149506         0.585635     0.490741
               전체  생존자 수  여성의 수  생존 여성의 수
First class   323    200    144       139
Second class  277    119    106        94
Third class   709    181    216       106


In [14]:
table_woman_prob

전체 대비 생존 여성 비율  전체 생존자 중 여성의 비율  여성 중 생존자 비율
First class         0.430341         0.695000     0.965278
Second class        0.339350         0.789916     0.886792
Third class         0.149506         0.585635     0.490741

In [15]:
table_woman

전체  생존자 수  여성의 수  생존 여성의 수
First class   323    200    144       139
Second class  277    119    106        94
Third class   709    181    216       106

### Q5: 부모 자식, 형제 동승여부에 따른 생존율을 구하고 비교하시오

In [16]:
data3 = data_origin[["survived","sibsp","parch","sex"]]
print(data3.head())

   survived  sibsp  parch     sex
0         1      0      0  female
1         1      1      2    male
2         0      1      2  female
3         0      1      2    male
4         0      1      2  female


In [17]:
sib_true_prob = len(data3.loc[(data3["sibsp"]!=0)&(data3["survived"]!=0),:])/len(data3.loc[data3["sibsp"]!=0,:])
print(sib_true_prob)
sib_false_prob = len(data3.loc[(data3["sibsp"]==0)&(data3["survived"]!=0),:])/len(data3.loc[data3["sibsp"]==0,:])
print(sib_false_prob)
sib_bool = np.array([sib_true_prob,sib_false_prob])

parch_true_prob=len(data3.loc[(data3["parch"]!=0)&(data3["survived"]!=0),:])/len(data3.loc[data3["parch"]!=0,:])
print(parch_true_prob)
parch_false_prob=len(data3.loc[(data3["parch"]==0)&(data3["survived"]!=0),:])/len(data3.loc[data3["parch"]==0,:])
print(parch_false_prob)
par_bool = np.array([parch_true_prob, parch_false_prob])

both_true = data3.loc[(data3["sibsp"]!=0)&(data3["parch"]!=0),:]
both_true_prob = len(both_true[both_true["survived"]==1])/len(both_true)
print(both_true_prob)
both_false = data3.loc[(data3["sibsp"]==0)&(data3["parch"]==0),:]
both_false_prob = len(both_false[both_false["survived"]==1])/len(both_false)
print(both_false_prob)
both_bool=np.array([both_true_prob, both_false_prob])

0.4569377990430622
0.3468013468013468
0.5342019543973942
0.33532934131736525
0.4563106796116505
0.30253164556962026


In [18]:
fam_combine = np.array([sib_bool,par_bool,both_bool])
cols_name = ["유","무"]
ind_name = ["형제","부모 자식","둘 다"]

table_fam = pd.DataFrame(fam_combine,columns=cols_name,index = ind_name).T
print(table_fam)

         형제     부모 자식       둘 다
유  0.456938  0.534202  0.456311
무  0.346801  0.335329  0.302532


In [19]:
table_fam

형제     부모 자식       둘 다
유  0.456938  0.534202  0.456311
무  0.346801  0.335329  0.302532

In [20]:
col_rename = {"sibsp":"형제 수"}
data3 = data3.rename(columns=col_rename)
survive_mean = data3["survived"].groupby(data3["형제 수"])
survive_mean_table = survive_mean.mean().to_frame()



col_rename = {"survived":"생존율"}
table_sib_mean = survive_mean_table.rename(columns=col_rename)
print(table_sib_mean)

           생존율
형제 수          
0     0.346801
1     0.510972
2     0.452381
3     0.300000
4     0.136364
5     0.000000
8     0.000000


In [21]:
table_sib_mean

생존율
형제 수          
0     0.346801
1     0.510972
2     0.452381
3     0.300000
4     0.136364
5     0.000000
8     0.000000

In [22]:
col_rename = {"parch":"부모 자식 수"}
data3 = data3.rename(columns=col_rename)
survive_mean2 = data3["survived"].groupby(data3["부모 자식 수"])
survive_mean_table2 = survive_mean2.mean().to_frame()



col_rename = {"survived":"생존율"}
table_par_mean = survive_mean_table2.rename(columns=col_rename)
print(table_par_mean)

              생존율
부모 자식 수          
0        0.335329
1        0.588235
2        0.504425
3        0.625000
4        0.166667
5        0.166667
6        0.000000
9        0.000000
